### ISSUE TITLE
Não é possível entrar nas páginas de listagem sem usuário ou estudante cadastrados

### ISSUE THREAD

**Issue by vinicius-o-souza** [hunkOraboni/SalaDeAula#9]
Quando solicitado a visualizacao dos usuarios ou estudantes e nao possui nenhum registro, gera um erro

**Comment by makotocchi** [comment]
Erro em questão:  
`Fatal error: Cannot use object of type Lista as array in C:\xampp\htdocs\SalaDeAula\class\controller\ListaUsuario.class.php on line 25`
